### ISSUE TITLE
Tracking read-to-transcript assignment 

### ISSUE THREAD

**Issue by sunsetyerin** [GoekeLab/bambu#332] opened 2022-11-01 18:55 UTC
Hi, @andredsim @cying111 

I want to use the feature of Bambu tracking read IDs.
From the previous [issue](https://github.com/GoekeLab/bambu/issues/236), it appears like a different branch is merged into the feature.
Wonder if the feature is merged into the main branch.

**Comment by sunsetyerin** [comment] 2022-11-02 06:21
<img width="729" alt="image" src="https://user-images.githubusercontent.com/59498491/199412959-9ca07fd9-58b7-43b9-a62b-3eebe459fb7d.png">

Can you please help me with solving the error?

**Comment by cying111** [comment] 2022-11-02 06:28
Hi @sunsetyerin , this is caused by a bug in the quantification step related to multiple assignment across genes, we are working on this now and will get back soon.

**Comment by sunsetyerin** [comment] 2022-11-03 18:53
@cying111, okay then please let me know if the update is finished

**Comment by cying111** [comment] 2022-11-04 07:23
Hi @sunsetyerin , the bug is now fixed in the master branch, you may try to re-run your sample. Let us know if the same error perists or there are any other errors! 
Thank you

**Comment by sunsetyerin** [comment] 2022-11-05 06:20
@cying111 thank you so much.
Was able to run bambu and got se object with readIDs but is there any ways I can match read IDs with gene IDs?

**Comment by andredsim** [comment] 2022-11-07 01:22
Hi, 

Since you already ran bambu with TrackReads = TRUE, you can access the read id to genes map using metadata(se)$readToTranscriptMaps.
Under the column equal matches, is the index for the gene found in rowRanges(se).

**Closed** 2022-12-07 01:48 UTC
